name: convert md
on:
  push:
    # branches: [ main ]
  pull_request:


jobs:
  convert-md:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: show checked out content and disk free
        run: |
          ls -l
          df -h
      - name: cat README.md into env var
        run: cat README.md 

