name: convert md
on:
  push:
    # branches: [ main ]
  pull_request:


jobs:
  convert-md:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: show checked out content and disk free
        run: |
          ls -l
          df -h
      - name: cat README.md into env var
        id: readme
        run: | 
          RM=$(cat README.md)
          echo "README=$RM" >> $GITHUB_ENV
        
      - name: show step readme
        run: echo ${{ env.README }}
      
      - name: convert README
        uses: lifepal/markdown-to-html@v1.1
        with: 
          text: ${{ env.README }}
          
        
      

