name: Feed Docker Image CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ "self-hosted", "linux", "arm64", "ondemand" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Compile docker image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/alpine/Dockerfile
          platforms: linux/arm64
          push: false
          load: false
